FROM ptoceti/jenkins:2.182-centos

MAINTAINER Laurent Thil

LABEL maintainer="lthil" \
    io.k8s.description="Jenkins 2 master node solo" \
    io.k8s.display-name="Jenkins 2 master"

ARG MAVEN_CENTRAL_REPO=https://repo1.maven.org/maven2
ARG NPMJS_REPO=https://registry.npmjs.org

ENV MAVEN_CENTRAL_REPO=${MAVEN_CENTRAL_REPO} \
    NPMJS_REPO=$[NPMJS_REPO]

USER root

RUN mkdir /var/cache/jenkins \
    && chown -R jenkins:jenkins /var/cache/jenkins

COPY src/init/groovy/initialsetup.groovy /usr/share/jenkins/ref/init.groovy.d/initialsetup.groovy.override
COPY src/conf/resources/conf/logging.properties /usr/share/jenkins/ref/conf/logging.properties.override
COPY src/conf/resources/jenkins-kubernetes.yaml /usr/share/jenkins/ref/jenkins.yaml.override

ENV JENKINS_UC=https://updates.jenkins.io/stable-2.176/update-center.json \
    INITIALSETUP_JENKINS_UPDATESITE_URL=https://updates.jenkins.io/stable-2.176/update-center.json \
    INITIALSETUP_JUL_LOGFILEPATH=/var/jenkins_home/logs \
    INITIALSETUP_JENKINS_JUL_CONFIGFILE=/var/jenkins_home/logging.properties

COPY src/conf/resources/usersettings/settings.xml /usr/share/jenkins/ref/.m2/settings.xml.override
COPY src/conf/resources/usersettings/.npmrc /usr/share/jenkins/ref/.npmrc.override

COPY src/conf/resources/conf/plugins-kubernetes.txt /usr/share/jenkins/ref/plugins.txt

RUN chown -R jenkins:jenkins /usr/share/jenkins/ref

USER jenkins

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

ENV JENKINS_OPTS="--webroot=/var/cache/jenkins/war"
