FROM jenkins/jenkins:2.182-centos

MAINTAINER Laurent Thil

LABEL maintainer="lthil" \
    io.openshift.tags="jenkins" \
    io.openshift.expose-services="8080:tcp" \
    io.k8s.description="Jenkins 2 master node with java tooling" \
    io.k8s.display-name="Jenkins 2 master"

ARG MAVEN_CENTRAL_REPO=https://repo1.maven.org/maven2
ARG NPMJS_REPO=https://registry.npmjs.org

ENV MAVEN_CENTRAL_REPO=${MAVEN_CENTRAL_REPO} \
    NPMJS_REPO=$[NPMJS_REPO]

USER root

RUN mkdir /opt/maven \
    && cd /opt/maven \
    && curl -fsSL -O https://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz \
    && tar xzvf apache-maven-3.5.4-bin.tar.gz \
    && rm apache-maven-3.5.4-bin.tar.gz \
    && curl -fsSL -O https://www-eu.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz \
    && tar xzvf apache-maven-3.6.1-bin.tar.gz \
    && rm apache-maven-3.6.1-bin.tar.gz

RUN mkdir /opt/java \
    && cd /opt/java \
    && curl -fSL -o adoptopenjdk8-info.json 'https://api.adoptopenjdk.net/v2/info/releases/openjdk8?os=linux&arch=x64&heap_size=normal&openjdk_impl=hotspot&type=jdk&release=jdk8u222-b10' \
    && curl -fSL -O $( cat adoptopenjdk8-info.json | grep "binary_link" | grep -Eo '(http|https)://[^"]+' | head -1) \
    && tar xzf $( cat adoptopenjdk8-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1) \
    && rm $( cat adoptopenjdk8-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1) \
    && curl -fSL -o adoptopenjdk9-info.json 'https://api.adoptopenjdk.net/v2/info/releases/openjdk9?os=linux&arch=x64&heap_size=normal&openjdk_impl=hotspot&type=jdk&release=jdk-9%2B181' \
    && curl -fSL -O $( cat adoptopenjdk9-info.json | grep "binary_link" | grep -Eo '(http|https)://[^"]+' | head -1) \
    && tar xzf $( cat adoptopenjdk9-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1) \
    && rm $( cat adoptopenjdk9-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1) \
    && curl -fSL -o adoptopenjdk10-info.json 'https://api.adoptopenjdk.net/v2/info/releases/openjdk10?os=linux&arch=x64&heap_size=normal&openjdk_impl=hotspot&type=jdk&release=jdk-10.0.2%2B13.1' \
    && curl -fSL -O $( cat adoptopenjdk10-info.json | grep "binary_link" | grep -Eo '(http|https)://[^"]+' | head -1) \
    && tar xzf $( cat adoptopenjdk10-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1) \
    && rm $( cat adoptopenjdk10-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1) \
    && curl -fSL -o adoptopenjdk11-info.json 'https://api.adoptopenjdk.net/v2/info/releases/openjdk11?os=linux&arch=x64&heap_size=normal&openjdk_impl=hotspot&type=jdk&release=jdk-11.0.4%2B11' \
    && curl -fSL -O $( cat adoptopenjdk11-info.json | grep "binary_link" | grep -Eo '(http|https)://[^"]+' | head -1) \
    && tar xzf $( cat adoptopenjdk11-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1) \
    && rm $( cat adoptopenjdk11-info.json | grep "binary_name" | grep -Eo '(OpenJDK)[^"]+' | head -1)

RUN mkdir /var/cache/jenkins \
    && chown -R jenkins:jenkins /var/cache/jenkins

USER jenkins

COPY src/init/groovy/initialsetup.groovy /usr/share/jenkins/ref/init.groovy.d/initialsetup.groovy.override
COPY src/conf/resources/conf/logging.properties /usr/share/jenkins/ref/conf/logging.properties.override
COPY src/conf/resources/jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml.override
COPY src/conf/resources/jenkins-slaves.yaml /usr/share/jenkins/ref/jenkins-slaves.yaml.override
COPY src/conf/resources/jenkins-docker-agents.yaml /usr/share/jenkins/ref/jenkins-docker-agents.yaml.override

ENV JENKINS_UC=https://updates.jenkins.io/stable-2.176/update-center.json \
    INITIALSETUP_JENKINS_UPDATESITE_URL=https://updates.jenkins.io/stable-2.176/update-center.json \
    INITIALSETUP_JUL_LOGFILEPATH=/var/jenkins_home/logs \
    INITIALSETUP_JENKINS_JUL_CONFIGFILE=/var/jenkins_home/logging.properties

COPY src/conf/resources/conf/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt


COPY src/conf/resources/usersettings/settings.xml /usr/share/jenkins/ref/.m2/settings.xml.override
COPY src/conf/resources/usersettings/.npmrc /usr/share/jenkins/ref/.npmrc.override


ENV JENKINS_OPTS="--webroot=/var/cache/jenkins/war"
