version: "3.7"
services:
  jenkins-master:
    build:
      context: ../
      dockerfile: ../Dockerfile-master
    image: ptoceti/jenkins-master:2.387.1-1
    container_name: ptoceti.jenkins-master
    ports:
    - "8080:8080"
    environment:
    - JAVA_OPTS=-Dinitialsetup.jenkins.admin.user=admin -Dinitialsetup.jenkins.admin.password=password
    - MAVEN_REPO=http://n/repository/public/
    - NPM_CONFIG_REGISTRY=http:///repository/npm-registry/
    volumes:
    - jenkins_master_home:/var/jenkins_home
    secrets:
    - jenkinsMaster
    - mavenDeployPassword
    - jenkins-master_id_rsa
    - maven-deploy-password
    - giteaJenkinsUserPassword
volumes:
  jenkins_master_home:
secrets:
  jenkinsMaster:
    file: ../src/conf/resources/secrets/jenkins-master/jenkins-master_id_rsa
  mavenDeployPassword:
    file: ../src/conf/resources/secrets/maven/maven-deploy-password
  jenkins-master_id_rsa:
    file: ../src/conf/resources/secrets/jenkins-master/jenkins-master_id_rsa
  maven-deploy-password:
   file: ../src/conf/resources/secrets/maven/maven-deploy-password
  giteaJenkinsUserPassword:
    file: ../src/conf/resources/secrets/gitea/gitea-jenkins-password

