version: "3.7"
services:
  jenkins-master:
    build:
      context: ../
      dockerfile: Dockerfile-centos-master
    image: ptoceti/jenkins-centos-master:latest
    container_name: ptoceti.jenkins-centos-master
    ports:
    - "8080:8080"
    environment:
    - JAVA_OPTS=-Dinitialsetup.jenkins.admin.user=admin -Dinitialsetup.jenkins.admin.password=password
    - MAVEN_REPO=http:///repository/public/
    - NPM_CONFIG_REGISTRY=http:///repository/npm-registry/
    - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins-slaves.yaml
    volumes:
      - jenkins_master_home:/var/jenkins_home
    secrets:
      - jenkins-master_id_rsa
      - mavenDeployPassword
    networks:
    - jenkins-udd
  jenkins-slave-1:
    build:
      context: ../
      dockerfile: Dockerfile-centos-slave-ssh
    image: ptoceti/jenkins-centos-slave-ssh:latest
    container_name: ptoceti-jenkins-centos-slave-1
    ports:
    - "10122:22"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY_SECRET=jenkinsmasterSshPubKey
    volumes:
    - jenkins_slave_1_home:/home/jenkins
    networks:
    - jenkins-udd
    secrets:
    - jenkinsmasterSshPubKey
  jenkins-slave-2:
    build:
      context: ../
      dockerfile: Dockerfile-centos-slave-ssh
    image: ptoceti/jenkins-centos-slave-ssh:latest
    container_name: ptoceti-jenkins-centos-slave-2
    ports:
    - "10222:22"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY_SECRET=jenkinsmasterSshPubKey
    volumes:
    - jenkins_slave_2_home:/home/jenkins
    networks:
    - jenkins-udd
    secrets:
    - jenkinsmasterSshPubKey
  jenkins-slave-3:
    build:
      context: ../
      dockerfile: Dockerfile-centos-slave-ssh
    image: ptoceti/jenkins-centos-slave-ssh:latest
    container_name: ptoceti-jenkins-centos-slave-3
    ports:
    - "10322:22"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY_SECRET=jenkinsmasterSshPubKey
    volumes:
    - jenkins_slave_3_home:/home/jenkins
    networks:
    - jenkins-udd
    secrets:
    - jenkinsmasterSshPubKey
volumes:
  jenkins_master_home:
    external: true
  jenkins_slave_1_home:
    external: true
  jenkins_slave_2_home:
    external: true
  jenkins_slave_3_home:
    external: true
secrets:
  jenkins-master_id_rsa:
    file: ~/secrets/jenkins-master/jenkins-master_id_rsa
  jenkinsmasterSshPubKey:
    file: ~/secrets/jenkins-master/jenkins-master_id_rsa.pub
  mavenDeployPassword:
    file: ~/secrets/maven/maven-deploy-password
networks:
  jenkins-udd:
